<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%	if(table.equals("jbqkb")){	%>
		<th>实验编码</th>
		<th>地址</th>
		<th>负责单位</th>
		<th>负责人</th>
		<th>联系电话</th>
		<th>email</th>
		<th>经度</th>
		<th>纬度</th>
		<th>海拔</th>
		<th>种植模式</th>
		<th>土壤质地</th>
		<th>土壤名称</th>
		<th>土壤英文名称</th>
		<th>备注</th>
		<th>创建人</th>
<%	} else if(table.equals("clmsb")){ %>
		<th>试验编码</th>
		<th>处理编号</th>
		<th>处理</th>
		<th>处理说明</th>
		<th>备注</th>
<%	} else if(table.equals("cstrwlsj")){ %>
		<th>试验编码</th>
		<th>采样重复序号</th>
		<th>土层</th>
		<th>土壤质地</th>
		<th>粘粒</th>
		<th>粉粒</th>
		<th>砂粒</th>
		<th>容重</th>
		<th>饱和导水率</th>
		<th>饱和含水量</th>
		<th>田间持水量</th>
		<th>凋萎系数</th>
		<th>导热率</th>
		<th>热容量</th>
		<th>CEC</th>
		<th>pH</th>
		<th>EC</th>
		<th>h1</th>
		<th>w1</th>
		<th>h2</th>
		<th>w2</th>
		<th>h3</th>
		<th>w3</th>
		<th>h4</th>
		<th>w4</th>
		<th>h5</th>
		<th>w5</th>
		<th>h6</th>
		<th>w6</th>
		<th>h7</th>
		<th>w7</th>
		<th>备注</th>
<%	} else if(table.equals("cstrhxsjbc")){ %>
		<th>试验编码</th>
		<th>采样重复序号</th>
		<th>采样日期</th>
		<th>土层</th>
		<th>有机质</th>
		<th>重组有机C</th>
		<th>轻组有机C</th>
		<th>全氮</th>
		<th>全磷</th>
		<th>全钾</th>
		<th>有效磷</th>
		<th>速效钾</th>
		<th>微生物碳</th>
		<th>微生物氮</th>
		<th>pH</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("cstrhxsjpm")){ %>
		<th>试验编码</th>
		<th>采样重复序号</th>
		<th>采样日期</th>
		<th>土层</th>
		<th>质量含水量</th>
		<th>硝态氮</th>
		<th>铵态氮</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("zzjlb")){ %>
		<th>试验编码</th>
		<th>茬口</th>
		<th>作物名称</th>
		<th>作物品种</th>
		<th>播种日期</th>
		<th>收获日期</th>
		<th>播种量</th>
		<th>千粒重</th>
		<th>播种深度</th>
		<th>播种方式</th>
		<th>出苗率</th>
		<th>株行距</th>
		<th>行向</th>
		<th>耕作方式</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("sfjlb")){ %>
		<th>试验编码</th>
		<th>处理编号</th>
		<th>茬口</th>
		<th>施肥日期</th>
		<th>肥料类型</th>
		<th>肥料名称</th>
		<th>施肥方式</th>
		<th>N</th>
		<th>P2O5</th>
		<th>K2O</th>
		<th>有机C</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("syqjlb")){ %>
		<th>试验编码</th>
		<th>处理编号</th>
		<th>茬口</th>
		<th>物候期</th>
		<th>日期始</th>
		<th>日期中</th>
		<th>日期止</th>
		<th>试验年度</th>
		<th>备注</th>	
<%	} else if(table.equals("gxsjb")){ %>
		<th>试验编码</th>
		<th>采样日期</th>
		<th>处理编号</th>
		<th>小区编号</th>
		<th>根鲜重</th>
		<th>根干重</th>
		<th>根长</th>
		<th>根的投影面积</th>
		<th>根的表面积</th>
		<th>根的平均直径</th>
		<th>根的体积</th>
		<th>根尖数</th>
		<th>根系照片</th>
		<th>试验年度</th>
		<th>备注</th>	
<%	} else if(table.equals("ggjlb")){ %>
		<th>试验编码</th>
		<th>处理编号</th>
		<th>茬口</th>
		<th>灌溉日期</th>
		<th>水源</th>
		<th>灌溉方式</th>
		<th>灌水量</th>
		<th>矿化度</th>
		<th>EC</th>
		<th>pH</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("ghsjb")){ %>
		<th>试验编码</th>
		<th>采样日期</th>
		<th>生育期</th>
		<th>处理编号</th>
		<th>小区编号</th>
		<th>叶片位置</th>
		<th>叶绿素含量</th>
		<th>叶片水势</th>
		<th>气孔导度</th>
		<th>净光合速率</th>
		<th>蒸腾速率</th>
		<th>胞间CO2浓度</th>	
<%	} else if(table.equals("trwlsjb")){ %>
		<th>试验编码</th>
		<th>处理编号</th>
		<th>小区编号</th>
		<th>取样日期</th>
		<th>采样重复序号</th>
		<th>土层</th>
		<th>容重</th>
		<th>饱和导水率</th>
		<th>导热率</th>
		<th>热容量</th>
		<th>CEC</th>
		<th>pH</th>
		<th>h1</th>
		<th>w1</th>
		<th>h2</th>
		<th>w2</th>
		<th>h3</th>
		<th>w3</th>
		<th>h4</th>
		<th>w4</th>
		<th>h5</th>
		<th>w5</th>
		<th>h6</th>
		<th>w6</th>
		<th>h7</th>
		<th>w7</th>
		<th>s1</th>
		<th>a1</th>
		<th>s2</th>
		<th>a2</th>
		<th>s3</th>
		<th>a3</th>
		<th>s4</th>
		<th>a4</th>
		<th>s5</th>
		<th>a5</th>
		<th>s6</th>
		<th>a6</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("trhxsjbc")){ %>
		<th>试验编码</th>
		<th>处理编号</th>
		<th>小区编号</th>
		<th>取样位置</th>
		<th>采样日期</th>
		<th>土层</th>
		<th>有机质</th>
		<th>重组有机C</th>
		<th>轻组有机C</th>
		<th>全氮</th>
		<th>全磷</th>
		<th>全钾</th>
		<th>有效磷</th>
		<th>速效钾</th>
		<th>微生物碳</th>
		<th>微生物氮</th>
		<th>pH</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("trhxsjpm")){ %>
		<th>试验编码</th>
		<th>处理编号</th>
		<th>小区编号</th>
		<th>取样位置</th>
		<th>采样日期</th>
		<th>土层</th>
		<th>质量含水量</th>
		<th>硝态氮</th>
		<th>铵态氮</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("trpmsfdtsjb")){ %>
		<th>试验编码</th>
		<th>日期</th>
		<th>处理编号</th>
		<th>小区编号</th>
		<th>土层深度</th>
		<th>体积含水率</th>
		<th>土壤温度</th>
		<th>盐分</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("trsrydtsjb")){ %>
		<th>试验编码</th>
		<th>日期时间</th>
		<th>处理编号</th>
		<th>小区编号</th>
		<th>探头位置</th>
		<th>port1电压</th>
		<th>port1温度</th>
		<th>port1盐分</th>
		<th>port2电压</th>
		<th>port2温度</th>
		<th>port2盐分</th>
		<th>port3电压</th>
		<th>port3温度</th>
		<th>port3盐分</th>
		<th>port4电压</th>
		<th>port4温度</th>
		<th>port4盐分</th>
		<th>port5电压</th>
		<th>port5温度</th>
		<th>port5盐分</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("wsqtcdb")){ %>
		<th>试验编码</th>
		<th>采样日期</th>
		<th>处理编号</th>
		<th>小区编号</th>
		<th>植物CO2排放速率</th>
		<th>植物CH4排放速率</th>
		<th>植物N2O排放速率</th>
		<th>土壤CO2排放速率</th>
		<th>土壤CH4排放速率</th>
		<th>土壤N2O排放速率</th>
		<th>表层土壤温度</th>
		<th>土壤含水量</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("zzypb")){ %>
		<th>试验编码</th>
		<th>采样日期</th>
		<th>生育期</th>
		<th>处理编号</th>
		<th>小区编号</th>
		<th>株高</th>
		<th>茎粗</th>
		<th>叶片数</th>
		<th>地上部鲜重</th>
		<th>地上部干重</th>
		<th>分蘖数</th>
		<th>叶面积指数</th>
		<th>光合有效辐射</th>
		<th>冠层温度</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("kzb")){ %>
		<th>试验编码</th>
		<th>处理编号</th>
		<th>小区编号</th>
		<th>取样日期</th>
		<th>株高</th>
		<th>茎粗</th>
		<th>叶片数</th>
		<th>旗叶面积</th>
		<th>有效分蘖数</th>
		<th>穗数</th>
		<th>穗粒数</th>
		<th>穗长</th>
		<th>玉米秃尖长</th>
		<th>玉米穗行数</th>
		<th>玉米穗直径</th>
		<th>千粒重</th>
		<th>籽粒产量</th>
		<th>生物产量</th>
		<th>籽粒含水率</th>
		<th>N</th>
		<th>P</th>
		<th>K</th>
		<th>试验年度</th>
		<th>备注</th>
<%	} else if(table.equals("qxsjb")){ %>
		<th>日期
		<th>降水量
		<th>蒸发皿蒸发量E601
		<th>蒸发皿蒸发量$20
		<th>净辐射
		<th>日照时数
		<th>十米高风速
		<th>最高气温
		<th>最低气温
		<th>平均气温
		<th>空气相对湿度
		<th>0cm地温
		<th>5cm地温
		<th>10cm地温
		<th>15cm地温
		<th>20cm地温
		<th>40cm地温
		<th>80cm地温
		<th>160cm地温
		<th>320cm地温
		<th>试验年度
		<th>备注
<%	} %>